"""atualizando compo tabela nome

Revision ID: 2f8b49fd58c6
Revises: 8477e11951d4
Create Date: 2025-06-09 16:47:48.286757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8b49fd58c6'
down_revision: Union[str, None] = '8477e11951d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
